### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by GanQiao1990** [suchanek/proteusPy#13]
Attempting uninstall: vtk
    Found existing installation: vtk 9.0.3
error: uninstall-distutils-installed-package

× Cannot uninstall vtk 9.0.3
╰─> It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
make: *** [makefile:69: install] Error 1

**Comment by suchanek** [comment]
Hi,
Can you tell me what platform you're on? VTK is installed directly after environment creation. Not sure where the older version is leaking in from...

Thanks,
Eric Suchanek

**Comment by GanQiao1990** [comment]
thanks for your responds, but When I install VTK from pip and comment out [#@$(CONDA) install vtk==9.2.6 -y], that works, but there's a new error:
WARNING: Did not find branch or tag 'egs_ssbond_240305', assuming revision or ref.
error: subprocess-exited-with-error
× git rev-parse HEAD did not run successfully.
│ exit code: 128
╰─> [2 lines of output]
HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git [...] -- [...]'
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× git rev-parse HEAD did not run successfully.
│ exit code: 128
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [makefile:69: install] Error 1

**Comment by GanQiao1990** [comment]
> thanks for your responds, but When I install VTK from pip and comment out [#@$(CONDA) install vtk==9.2.6 -y], that works, but there's a new error: WARNING: Did not find branch or tag 'egs_ssbond_240305', assuming revision or ref. error: subprocess-exited-with-error × git rev-parse HEAD did not run successfully. │ exit code: 128 ╰─> [2 lines of output] HEAD fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git [...] -- [...]' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × git rev-parse HEAD did not run successfully. │ exit code: 128 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip. make: *** [makefile:69: install] Error 1

in my opinion, the makefile should be change in two place for the install sucessed.
1.the vtk install should be check, and install out of makefile by pip.
2.biopython install in the makefile should be correct by comment out as '#@egs_ssbond_240305'

**Comment by suchanek** [comment]
Hi there,
Thanks for the comments. The current dev branch removes Biopython entirely. If you uncomment the vtk in the makefile, and remove the vtk line in setup.py it should install. I will be pushing the dev branch soon. It seems you’re in Linux? The PC and Mac installs work normally for me.
