### ISSUE TITLE
JOSS review - License file

### ISSUE THREAD

**Issue by AnjaConev** [suchanek/proteusPy#3]
Please make sure that your license file is named correctly.
You have a valid BSD2 license in the markdown file https://github.com/suchanek/proteusPy/blob/master/License.md 

It seems that for the JOSS purposes it should the file should be https://github.com/suchanek/proteusPy/blob/master/LICENSE 
You just have to rename the file.
Thanks! 😄

**Comment by suchanek** [comment]
Got it, will be in next push.

**Comment by AnjaConev** [comment]
Looks great, thank you for doing this!
