### ISSUE TITLE
JOSS review - widgets not rendering 

### ISSUE THREAD

**Issue by AnjaConev** [suchanek/proteusPy#5]
When I try to render any of the widgets in the Jupyter Notebooks I get errors.

For example, when I run the second cell of `notebooks/Display_SS.ipynb`, I get:

![image](https://github.com/suchanek/proteusPy/assets/7367905/307c1a7b-3105-4854-95ca-bdab094022c3)

**Comment by AnjaConev** [comment]
This error might be related to the platform on which I am running this right now.
I was testing the tool on Windows 10 with the WSL2 (Linux subsystem).
I do not have access to a different platform right now. 
I will try again later on a Linux desktop and let you know if I have any luck.

**Comment by suchanek** [comment]
thank you. this is definitely an OpenGL/gpu issue, probably related to WSL. I will try to write up some Windows specific docs. It does run fine under Windows 10.

**Comment by suchanek** [comment]
Ok I confirmed it won't run under wsl. I do have it running fine under windows 11 virtual machine on my mac. lol

**Comment by suchanek** [comment]
I'm closing this since I think it's wsl only and will make a note in the docs.

**Comment by AnjaConev** [comment]
Yes, it is an issue with wsl - checked on a regular linux and everything worked smoothly!
