### ISSUE TITLE
JOSS review - tests

### ISSUE THREAD

**Issue by AnjaConev** [suchanek/proteusPy#6]
If possible, please provide some tests for different modules of your package!

Thanks! 🎄 😄

**Comment by suchanek** [comment]
I have a few display tests already and will call those out. Also, you can test each python source program of the package itself by running them, since I've used docstrings throughout. The best overall notebook to run is DisulfideAnalysis.ipynb, since it thoroughly exercises the package. Cheers!

**Comment by suchanek** [comment]
I am writing a program to run through the modules. In progress.

**Comment by suchanek** [comment]
I've decided to use make to ease install and testing. I have the doctest testing integrated now.

**Comment by AnjaConev** [comment]
Perfect!! One more thing - would it be possible to add the instructions for resting in the readme too - just in case someone else wants to run the tests too. Maybe they are already somewhere and I missed something?

**Comment by suchanek** [comment]
Done. Adding the testing allowed me to catch a few problems with the animation rendering. 👍
