### ISSUE TITLE
JOSS review - software paper - current state of the field

### ISSUE THREAD

**Issue by AnjaConev** [suchanek/proteusPy#7]
Could you give a more extensive overview of the current state of the field?
You mention that your database is the first database of disulfide bonds to your knowledge.
I found a part of biotite package that can visualize disulfide bonds to some (limited) extent https://www.biotite-python.org/examples/gallery/structure/disulfide_bonds.html 
Is there any other software that calculates/visualizes the disulfide bonds of the PDB files?

Thanks! 😸

**Comment by suchanek** [comment]
I'll have a look. There are a number of programs that calculate overall structural parameters, RCSB uses a few to calculate overall structural validity. I haven't seen an aggregated database yet. thanks for the comments.

**Comment by suchanek** [comment]
There is a multitude of programs to visualize protein structures. The unique aspect of the database is that it's a coherent extract of all disulfide bond containing structures in the RCSB. I haven't seen any other database like it. Thoughts?

**Comment by suchanek** [comment]
Very good.
